# 전환이 일어난 유저(cart or purchase)에게 전환율으로 추천

전환율 식 : 

ex)

|유저|cart|purchase|view|
|------|---|---|---|
|id|1|1|4|

위의 유저에게 (cart / view) + (purchase / view)을 적용

즉

$\frac{1}{4} + \frac{1}{4} = 0.5$

|유저|cart|purchase|view|ratio|
|------|---|---|---|---|
|id|1|1|4|0.5|

적용

# 라이브러리 로드

In [1]:
!pip install implicit
!pip install fastparquet

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 18.6 MB 2.0 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.5 MB 2.1 MB/s 
     |████████████████████████████████| 1.6 MB 55.1 MB/s 


In [2]:
import pandas as pd
import numpy as np
import scipy.sparse as sparse
import random
import implicit

from tqdm import tqdm

# 데이터 로드

In [3]:
try:
  path = 'C:/Users/User/Desktop/AIB_13/CP2/data/'
  df = pd.read_parquet(path + 'light_2019-Oct.parquet', engine='fastparquet')
except:
  path = '/content/drive/MyDrive/CP2/data/'
  df = pd.read_parquet(path + 'light_2019-Oct.parquet', engine='fastparquet')

In [4]:
df.head()

event_time event_type  product_id  category_id  \
0  2019-10-01 00:00:00 UTC       view    44600062   -251657396   
1  2019-10-01 00:00:00 UTC       view     3900821   -780140327   
2  2019-10-01 00:00:01 UTC       view    17200506  -1904213353   
3  2019-10-01 00:00:01 UTC       view     1307067   1518338663   
4  2019-10-01 00:00:04 UTC       view     1004237  -1769995873   

                         category_code     brand        price    user_id  \
0                                  NaN  shiseido    35.790001  541312140   
1  appliances.environment.water_heater      aqua    33.200001  554748717   
2           furniture.living_room.sofa       NaN   543.099976  519107250   
3                   computers.notebook    lenovo   251.740005  550050854   
4               electronics.smartphone     apple  1081.979980  535871217   

                           user_session  
0  72d76fde-8bb3-4e00-8c23-a032dfed738c  
1  9333dfbd-b87a-4708-9857-6336556b0fcc  
2  566511c2-e2e3-422b-b695-cf8e6e792ca8  
3  7c90fc70-0e80-4590-96f3-13c02c18c713  
4  c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [5]:
data = df[['user_id','product_id','event_type']]

# 데이터 전처리

## cart, purchase가 존재하는 유저 데이터 추출

1. event_type 컬럼에 cart가 존재하는 user_id 추출
2. event_type 컬럼에 purchase가 존재하는 user_id 추출
3. 위에서 구한 id 합치기

In [6]:
cart_user_id = set(data.loc[data['event_type'] == 'cart','user_id'].unique())
purchase_user_id = set(data.loc[data['event_type'] == 'purchase', 'user_id'].unique())

all_id = cart_user_id.union(purchase_user_id)

In [7]:
data = data.loc[data['user_id'].isin(all_id)].reset_index(drop=True)

In [8]:
data['event_type'] = data['event_type'].astype('object')

## 전환율 적용

전환율 식 : 

|유저|cart|purchase|view|
|------|---|---|---|
|id|1|1|4|

위의 유저에게 (cart / view) + (purchase / view)을 적용

즉

$\frac{1}{4} + \frac{1}{4} = 0.5$

|유저|cart|purchase|view|ratio|
|------|---|---|---|---|
|id|1|1|4|0.5|

In [9]:
grouped = data.groupby(['user_id','product_id','event_type'])['event_type'].count()
grouped = pd.DataFrame(grouped).rename(columns={'event_type' : 'count'}).reset_index()

In [10]:
table = grouped.pivot_table(index=['user_id','product_id'], columns=['event_type'], values=['count'])
table = table.reset_index()
table.columns = ['user_id','product_id','cart','purchase','view']
table = table.fillna(0)

In [11]:
table['cart'] = table['cart'].astype('int')
table['purchase'] = table['purchase'].astype('int')
table['view'] = table['view'].astype('int')

In [12]:
table.head()

user_id  product_id  cart  purchase  view
0  264649825     8500081     0         0     1
1  264649825     8500083     0         1    12
2  264649825     8500084     0         1     4
3  264649825     8500086     0         0     2
4  264649825    27700136     0         0     1

table을 확인했을때 view 값이 0인 값이 존재했습니다.  
이것의 의미는 수집된 시점이전에 view를 했거나,  
제품의 상세 페이지에 방문하지 않고 바로 전환이 일어났다고 가정하여, 평균값이 `2`를 넣어주겠습니다.

In [13]:
table.loc[table['view'] == 0, 'view'] = 2

In [14]:
table['cart_conversion'] = table['cart'] / table['view']
table['purcahse_conversion'] = table['purchase'] / table['view']
table['ratio'] = table['cart_conversion'] + table['purcahse_conversion']

In [15]:
table['ratio'] = table['ratio'].apply(lambda x : round(x, 2))

In [16]:
table.head()

user_id  product_id  cart  purchase  view  cart_conversion  \
0  264649825     8500081     0         0     1              0.0   
1  264649825     8500083     0         1    12              0.0   
2  264649825     8500084     0         1     4              0.0   
3  264649825     8500086     0         0     2              0.0   
4  264649825    27700136     0         0     1              0.0   

   purcahse_conversion  ratio  
0             0.000000   0.00  
1             0.083333   0.08  
2             0.250000   0.25  
3             0.000000   0.00  
4             0.000000   0.00

In [17]:
data = table[['user_id','product_id','ratio']]

# Item Lookup(product lookup) 테이블 만들기

In [18]:
product_lookup = df[['product_id','category_code','brand']].drop_duplicates('product_id').reset_index(drop=True).sort_values('product_id')
product_lookup.head()

product_id           category_code    brand
151915     1000978  electronics.smartphone      NaN
8437       1001588  electronics.smartphone    meizu
85152      1001606  electronics.smartphone    apple
32556      1002042  electronics.smartphone  samsung
9400       1002062  electronics.smartphone  samsung

# Rating Matrix 만들기

In [19]:
num_user = data['user_id'].nunique()
num_item = data['product_id'].nunique()

num_user, num_item

(481458, 148488)

In [20]:
users = list(np.sort(data['user_id'].unique()))
products = list(data['product_id'].unique())
ratio = list(data['ratio'])

rows = data['user_id'].astype('category').cat.codes
data['user_id_code'] = data['user_id'].astype('category').cat.codes

cols = data['product_id'].astype('category').cat.codes
data['product_id_code'] = data['product_id'].astype('category').cat.codes

len(users), len(products), len(ratio)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


(481458, 148488, 7942703)

In [21]:
user_item_matrix = sparse.csr_matrix((ratio, (rows, cols)), shape=(num_user, num_item))
user_item_matrix

<481458x148488 sparse matrix of type '<class 'numpy.float64'>'
	with 7942703 stored elements in Compressed Sparse Row format>

# 추천 시스템 class 구현

In [22]:
from implicit.als import AlternatingLeastSquares
from sklearn import metrics
class MyALS():
  """
  implicit 라이브러리를 이용하여 필요한 기능을 담았습니다.

  Parameters
  ----------
  model : implicit 라이브러리의 AlternatingLeastSquares() 클래스로 생성된 인스턴스
  user_item_matrix : 사용자가 정의한 User-Item Matrix(Sparse Matrix)
  item_lookup : item(product)에 대한 정보를 담은 테이블
  data : User-Item Matrix를 만든 원본데이터

  """
  def __init__(self, model, user_item_matrix, item_lookup, data):

    self.model = model
    self.metrics_model = model
    self.user_item_matrix = user_item_matrix
    self.item_lookup = item_lookup
    self.data = data
  
  def test_lookup(self):
    display(self.item_lookup.head())
  def test_check_user_ind(self):
    print(self.zero_user_inds[:10])

  def fit(self, user_item_matrix):
    """
    행렬분해의 ALS를 이용하여 모델을 학습합니다.

    Parameters
    ----------
    user_item_matrix : 사용자가 정의한 User-Item Matrix(Sparse Matrix)
    """
    self.model.fit(user_item_matrix)
    
  def user_id_2_code(self, user_id):
    """
    입력받은 user_id를 User_Item_Matrix에 있는 user_id_code로 바꾸어주는 함수

    Parameters
    ----------
    user_id : 유저 ID

    """
    user_id_code = self.data.loc[self.data['user_id'] == user_id, 'user_id_code'].unique()[0]
    return user_id_code

  def product_id_2_code(self, product_id):
    """
    입력받은 product_id를 User-Item-Matrix에 있는 product_id_code로 바꾸어주는 함수

    Parameters
    ----------
    product_id : 상품 ID
    """
    product_id_code = self.data.loc[self.data['product_id'] == product_id, 'product_id_code'].unique()[0]
    return product_id_code

  def code_2_product_id(self, product_id_code):
    """
    입력받은 product_id_code를 User-Item-Matrix에 있는 product_id로 바꾸어주는 함수

    Parameters
    ----------
    product_id_code : 상품 ID code    
    """
    product_id = self.data.loc[self.data['product_id_code'] == product_id_code, 'product_id'].unique()[0]
    return product_id

  def get_recom_product(self, user_id, n = 10):
    """  
    user_id에 맞는 product를 n개 만큼 추천하여 데이터프레임 형태로 반환하는 함수

    Parameters
    ----------
    user_id : 유저 ID
    n : 추천 받게 될 item의 수
    """ 

    # user_id_2_code 함수를 이용하여 유저의 ID를 user_id_code로 변환합니다
    user_id_code = self.user_id_2_code(user_id)
  
    # model의 recommend를 이용하여 추천받는 제품의 id를 추출합니다.
    # 이때 추천 받는 제품의 id는 product_id가 아니라 product_id_code 입니다.
    recommended = self.model.recommend(user_id_code, self.user_item_matrix[user_id_code], N=n)[0]
    #결과를 담을 리스트를 초기화 합니다.
    results = []
    # 추천 받은 id를 돌면서 item_lookup 테이블에서 해당 product의 정보를 찾아 결과에 담습니다.
    for product_id_code in recommended:
      
      recommended_product_id = self.code_2_product_id(product_id_code)
      result = self.item_lookup.loc[self.item_lookup['product_id'] == recommended_product_id]
      results.append(result)
      
    return pd.concat(results)
  
  def get_user_topN_product(self,user_id,column, n = 20):
    """
    유저가 특정 기준값이 높은 제품 N개를 반환

    Parameters
    ----------
    user_id : 유저 ID
    column : 어떠한 값을 확인할 기준이 되는 컬럼
    n : 반환할 Item 수
    """

    product_ids = self.data.loc[self.data['user_id'] == user_id].sort_values(column, ascending=False)[:n]['product_id'].values
    product_values = self.data[self.data['user_id'] == user_id].sort_values(column, ascending=False)[:n][column].values
    results = []
    for i in product_ids:
      result = self.item_lookup.loc[self.item_lookup['product_id'] == i]
      results.append(result)
    frame = pd.concat(results)
    frame[column] = product_values

    return frame

  def get_explain(self, user_id, item_id, column):
    """
    사용자에게 제품이 추천된 이유를 반환하는 함수

    Parameters
    ----------
    user_id : 유저 ID
    item_id : Item(product) ID
    column : 확인할 컬럼
    """

    user_id_code = self.user_id_2_code(user_id)
    product_id_code = self.product_id_2_code(item_id)

    total_score, top_contributions, user_weights = self.model.to_cpu().explain(user_id_code, self.user_item_matrix, product_id_code)

    results = []
    categorys = []
    brands = []
    scores = []
    for id_, score_ in top_contributions:
      product_id = self.code_2_product_id(id_)
      result = self.data.loc[(self.data['product_id'] == product_id) & (self.data['user_id'] == user_id)][['user_id','product_id',column]]
      category = self.item_lookup.loc[self.item_lookup['product_id'] == product_id, 'category_code'].unique()[0]
      brand = self.item_lookup.loc[self.item_lookup['product_id'] == product_id, 'brand'].unique()[0]

      results.append(result)
      categorys.append(category)
      brands.append(brand)
      scores.append(score_)

    frame = pd.concat(results)
    frame['score'] = scores
    frame['category'] = categorys
    frame['brand'] = brands
    
    frame = frame[['user_id', 'product_id','category','brand',column, 'score']]
    return frame, total_score

  def get_train_test(self,percentage=.2, seed=42):
    test_set = self.user_item_matrix.copy()
    train_set = self.user_item_matrix.copy()

    test_set[test_set != 0] = 1

    nonzero_idxs = train_set.nonzero()
    nonzero_pairs = list(zip(nonzero_idxs[0], nonzero_idxs[1]))

    random.seed(seed)
    n_samples = int(np.ceil(percentage * len(nonzero_pairs)))
    samples = random.sample(nonzero_pairs, n_samples)

    user_idxs = [index[0] for index in samples]
    item_idxs = [index[1] for index in samples]

    train_set[user_idxs, item_idxs] = 0
    train_set.eliminate_zeros()

    self.zero_user_idxs = user_idxs
    self.zero_item_idxs = item_idxs
    self.train_set = train_set
    self.test_set = test_set
    

  def get_score(self, test_size =.2, seed=42, k = 10, method='hit_at_k'):
    # train, test로 데이터가 분리
    self.get_train_test(test_size, seed)
    # metrics_model이 학습
    self.metrics_model.fit(self.train_set)
    # 샘플 user를 랜덤으로 추출
    random_state = np.random.RandomState(seed)
    user_id_code_samples = random_state.choice(self.data['user_id_code'], 10000)
    if method == 'hit_at_k':
      scores = self.hit_at_k(user_id_code_samples, k)
    
    return scores
  def hit_at_k(self, user_id_code_samples, k):
    """
    k개의 추천 중 relevant한것(전환된 이력이 있다면 것==1)이 있다면 1, 아니면 0을 반환
    추천을 받은 user의 수 만큼 나누어줌

    Parameters
    ----------
    user_id_code_samples : 샘플링한 유저의 ID
    k : 추천할 아이템의 수
    """
    scores = []
    for user_id_code_sample in tqdm(user_id_code_samples):
      recommedation_ids = self.metrics_model.recommend(user_id_code_sample, self.train_set[user_id_code_sample], N=k)[0]
      results = []
      for id_ in recommedation_ids:
        result = self.test_set[user_id_code_sample, id_]
        results.append(result)

      if 1 in results:
        scores.append(1)
      else:
        scores.append(0)
    return np.mean(scores)
  
  def get_precision_score(self,y_true, y_pred):
    return metrics.precision_score(y_true, y_pred)

# 추천하기

In [23]:
model = MyALS(AlternatingLeastSquares(), user_item_matrix, product_lookup, data)

In [24]:
model.fit(user_item_matrix)

  0%|          | 0/15 [00:00<?, ?it/s]

In [25]:
data.sort_values('ratio', ascending=False)

user_id  product_id  ratio  user_id_code  product_id_code
7820967  563571758     4804295  113.0        460461            16524
944160   513236366    12707254   81.0         34140            48018
3723589  521963865     4804056   64.0        172706            16356
5875679  546907969     1004767   62.0        305741              796
7745574  562583155     1004565   55.0        450307              667
...            ...         ...    ...           ...              ...
2741480  516998984     3800979    0.0        117763            11582
2741479  516998984     3800816    0.0        117763            11513
2741478  516998984     1307373    0.0        117763             2506
2741477  516998984     1307344    0.0        117763             2479
3971351  524211546    21408842    0.0        187914            85669

[7942703 rows x 5 columns]

563571758 id의 유저는 4804295 id 제품에 대하여 113 전환율을 기록했습니다.

In [26]:
table.loc[table['user_id'] == 563571758]

user_id  product_id  cart  purchase  view  cart_conversion  \
7820965  563571758     1002099     0         0     1              0.0   
7820966  563571758     3801134     1         0     1              1.0   
7820967  563571758     4804295   113         0     1            113.0   

         purcahse_conversion  ratio  
7820965                  0.0    0.0  
7820966                  0.0    1.0  
7820967                  0.0  113.0

제품을 1번보고 113번 cart 담은것을 확인할 수 있습니다.

이 유저에게 제품을 추천하겠습니다.

In [27]:
user = 563571758
column = 'ratio'

model.get_user_topN_product(user, column)

product_id                category_code     brand  ratio
59       4804295  electronics.audio.headphone    xiaomi  113.0
3437     3801134              appliances.iron  elenberg    1.0
1495     1002099       electronics.smartphone   samsung    0.0

In [28]:
model.get_recom_product(user)

product_id           category_code     brand
1774     1005031  electronics.smartphone    xiaomi
735      1004709  electronics.smartphone    huawei
1912     1005161  electronics.smartphone    xiaomi
312      1004776  electronics.smartphone    xiaomi
989      6000094  auto.accessories.alarm  starline
5969     1004887  electronics.smartphone      oppo
707      1004247  electronics.smartphone     apple
103      5100855      electronics.clocks     apple
1726     5100503                     NaN    xiaomi
2107     1801805    electronics.video.tv     artel

In [29]:
explain_frame, total_score = model.get_explain(user, 1002532, column)
explain_frame

/usr/local/lib/python3.7/dist-packages/implicit/utils.py:29: UserWarning: OpenBLAS detected. Its highly recommend to set the environment variable 'export OPENBLAS_NUM_THREADS=1' to disable its internal multithreading
  "OpenBLAS detected. Its highly recommend to set the environment variable "


user_id  product_id                     category     brand  ratio  \
7820966  563571758     3801134              appliances.iron  elenberg    1.0   
7820965  563571758     1002099       electronics.smartphone   samsung    0.0   
7820967  563571758     4804295  electronics.audio.headphone    xiaomi  113.0   

            score  
7820966  0.006500  
7820965 -0.000000  
7820967 -0.000241

# 성능 평가하기

In [30]:
scores = model.get_score()

  0%|          | 0/15 [00:00<?, ?it/s]

100%|██████████| 10000/10000 [00:11<00:00, 853.41it/s]


In [31]:
print('hit at k(10) : ', round(scores, 2))

hit at k(10) :  0.02
